### ISSUE TITLE
The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.

### ISSUE THREAD

**Issue by kash456** [share-extras/twitter-dashlets#2]
Hi

We have been using the Twitter Feed Dashlet on Alfresco Community 4.0d for some time and recently get a message saying "An unknown error occurred fetching the Twitter feed"

When I take a closer look using firebug the message is:

{"errors": [{"message": "The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.", "code": 68}]}

Any help appreciated

Kind Regards

Kash

**Comment by wabson** [comment]
This is fixed in the latest code in Git. Are you able to help in testing it out?

**Comment by kash456** [comment]
Hi Will

I certainly am, I will download and build the latest code and deploy to our test servers tomorrow and let you know the result.  If there is anything else you need me to try out at the same time let me know.

Kash

**Comment by wabson** [comment]
Kash, were you able to try out those changes in the end?

**Comment by ilricca** [comment]
Hi Will, I've built the code and I've tested the dashlets: there is an issue, sadly.
Using Eclipse + Maven, in "localhost", the dashlets run fine but in the console there is the following error...

No EndPoint descriptor configuration found for ID: twitter-oauth

The same error is present in our test server, but here I have also a Surf error...

. .. ... ..... ... .. . .. ... ..... ... .. . .. ... ..... ... .. . .. ... ..... ... .. . .. ... ..... ... .. . .. ... ..... ... .. .

The Web Script /share/page/extras/oauth/auth-return has responded with a status of 500 - Internal Error.

500 Description:     An error inside the HTTP server which prevented it from fulfilling the request.

Message:    Connection timed out

Exception:  java.net.ConnectException - Connection timed out

java.net.PlainSocketImpl.socketConnect(Native Method)
java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
java.net.Socket.connect(Socket.java:529)
java.net.Socket.connect(Socket.java:478)
java.net.Socket.<init>(Socket.java:375)
java.net.Socket.<init>(Socket.java:249)
org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
org.sharextras.webscripts.OAuthReturn.requestAccessToken(OAuthReturn.java:345)
org.sharextras.webscripts.OAuthReturn.execute(OAuthReturn.java:140)
org.springframework.extensions.webscripts.PresentationContainer.executeScript(PresentationContainer.java:70)
org.springframework.extensions.webscripts.LocalWebScriptRuntimeContainer.executeScript(LocalWebScriptRuntimeContainer.java:240)
org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:377)
org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:209)
org.springframework.extensions.webscripts.servlet.mvc.WebScriptView.renderMergedOutputModel(WebScriptView.java:104)
org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:250)
org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1047)
org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:817)
org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719)
org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)
org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:549)
javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:646)
org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:436)
org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:374)
org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:302)
org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:195)
org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:159)
org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:141)
org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:90)
org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:417)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:602)
org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
java.lang.Thread.run(Thread.java:662)

Server: Spring WebScripts - v1.2.0 (Release 1173) schema 1,000
Time:   Nov 4, 2013 10:28:19 AM

Diagnostics:    Inspect Web Script (org/sharextras/slingshot/oauth-return.get)

. .. ... ..... ... .. . .. ... ..... ... .. . .. ... ..... ... .. . .. ... ..... ... .. . .. ... ..... ... .. . .. ... ..... ... .. .

Thanks, Andrea

**Comment by wabson** [comment]
This issue should no longer exist in v2.6.0 of the dashlets. Please note that if you build it from source, you must use the Ant build script as per the README. Maven is only used for publishing the artifacts which must first be build using Ant.
