### ISSUE TITLE
how to solve this problem

### ISSUE THREAD

**Issue by samynathan17** [share-extras/twitter-dashlets#5]
0 [main] DEBUG twitter4j.internal.http.HttpClientImpl  - Request: 
1 [main] DEBUG twitter4j.internal.http.HttpClientImpl  - GET http://search.twitter.com/search.json?q=%23CLT20&rpp=100&with_twitter_user_id=true&include_entities=true
4 [main] DEBUG twitter4j.auth.OAuthAuthorization  - OAuth base string: GET&http%3A%2F%2Fsearch.twitter.com%2Fsearch.json&include_entities%3Dtrue%26oauth_consumer_key%3DcmjujyaHMfTJEOylwjRElyS7F%26oauth_nonce%3D1965841355%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1467627342%26oauth_token%3D4825036615-lVnSOUfA0Q9scjQ2bwSDC4AvTIkDaUWDA6Dqo7h%26oauth_version%3D1.0%26q%3D%2523CLT20%26rpp%3D100%26with_twitter_user_id%3Dtrue
412 [main] DEBUG twitter4j.auth.OAuthAuthorization  - OAuth signature: KQGeDwH11/+3+wO/4QZN8BKa76E=
412 [main] DEBUG twitter4j.internal.http.HttpClientImpl  - Authorization: *******************************************************************************************************************************************************************************************************************************************************************************************
413 [main] DEBUG twitter4j.internal.http.HttpClientImpl  - X-Twitter-Client-Version: 2.2.5
413 [main] DEBUG twitter4j.internal.http.HttpClientImpl  - X-Twitter-Client-URL: http://twitter4j.org/en/twitter4j-2.2.5.xml
413 [main] DEBUG twitter4j.internal.http.HttpClientImpl  - X-Twitter-Client: Twitter4J
413 [main] DEBUG twitter4j.internal.http.HttpClientImpl  - User-Agent: twitter4j http://twitter4j.org/ /2.2.5
413 [main] DEBUG twitter4j.internal.http.HttpClientImpl  - Accept-Encoding: gzip
965 [main] DEBUG twitter4j.internal.http.HttpClientImpl  - Response: 
966 [main] DEBUG twitter4j.internal.http.HttpClientImpl  - date: Mon, 04 Jul 2016 10:15:43 GMT
966 [main] DEBUG twitter4j.internal.http.HttpClientImpl  - HTTP/1.1 410 Gone
966 [main] DEBUG twitter4j.internal.http.HttpClientImpl  - set-cookie: guest_id=v1%3A146762734335985535; Domain=.twitter.com; Path=/; Expires=Wed, 04-Jul-2018 10:15:43 UTC
966 [main] DEBUG twitter4j.internal.http.HttpClientImpl  - server: tsa_a
966 [main] DEBUG twitter4j.internal.http.HttpClientImpl  - content-length: 156
966 [main] DEBUG twitter4j.internal.http.HttpClientImpl  - x-response-time: 6
966 [main] DEBUG twitter4j.internal.http.HttpClientImpl  - x-connection-hash: d8332ee6a14e8b03b8e9c3358df521af
966 [main] DEBUG twitter4j.internal.http.HttpClientImpl  - content-encoding: gzip
966 [main] DEBUG twitter4j.internal.http.HttpClientImpl  - content-type: application/json;charset=utf-8
969 [main] DEBUG twitter4j.internal.http.HttpResponseImpl  - {"errors":[{"message":"The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.","code":64}]}

**Comment by wabson** [comment]
> The Twitter REST API v1 is no longer active. Please migrate to API v1.1.

I'd have thought that the error was pretty clear. In any case, this project does not use Twitter4J or indeed have anything to do with it, so I am closing this issue. Please take it up with the Twitter4J team.
